#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: 5424026
#
Name     : R-kimisc
Version  : 1.0.0
Release  : 41
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/kimisc_1.0.0.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/kimisc_1.0.0.tar.gz
Summary  : Kirill's Miscellaneous Functions
Group    : Development/Tools
License  : MIT
Requires: R-memoise
Requires: R-plyr
Requires: R-pryr
BuildRequires : R-memoise
BuildRequires : R-plyr
BuildRequires : R-pryr
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%prep
%setup -q -n kimisc
pushd ..
cp -a kimisc buildavx2
popd
pushd ..
cp -a kimisc buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1733327587

%install
export SOURCE_DATE_EPOCH=1733327587
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/kimisc/DESCRIPTION
/usr/lib64/R/library/kimisc/INDEX
/usr/lib64/R/library/kimisc/LICENSE
/usr/lib64/R/library/kimisc/Meta/Rd.rds
/usr/lib64/R/library/kimisc/Meta/features.rds
/usr/lib64/R/library/kimisc/Meta/hsearch.rds
/usr/lib64/R/library/kimisc/Meta/links.rds
/usr/lib64/R/library/kimisc/Meta/nsInfo.rds
/usr/lib64/R/library/kimisc/Meta/package.rds
/usr/lib64/R/library/kimisc/NAMESPACE
/usr/lib64/R/library/kimisc/NEWS.md
/usr/lib64/R/library/kimisc/R/kimisc
/usr/lib64/R/library/kimisc/R/kimisc.rdb
/usr/lib64/R/library/kimisc/R/kimisc.rdx
/usr/lib64/R/library/kimisc/help/AnIndex
/usr/lib64/R/library/kimisc/help/aliases.rds
/usr/lib64/R/library/kimisc/help/kimisc.rdb
/usr/lib64/R/library/kimisc/help/kimisc.rdx
/usr/lib64/R/library/kimisc/help/paths.rds
/usr/lib64/R/library/kimisc/html/00Index.html
/usr/lib64/R/library/kimisc/html/R.css
/usr/lib64/R/library/kimisc/staticdocs/index.R
/usr/lib64/R/library/kimisc/tests/test-all.R
/usr/lib64/R/library/kimisc/tests/testthat.R
/usr/lib64/R/library/kimisc/tests/testthat/scripts/thisfile-cat.R
/usr/lib64/R/library/kimisc/tests/testthat/scripts/thisfile.R
/usr/lib64/R/library/kimisc/tests/testthat/test-cut.R
/usr/lib64/R/library/kimisc/tests/testthat/test-gdiff.R
/usr/lib64/R/library/kimisc/tests/testthat/test-list_to_df.R
/usr/lib64/R/library/kimisc/tests/testthat/test-thisfile.R
/usr/lib64/R/library/kimisc/tests/testthat/test-vswitch.R
